<!--#include file="hhconn.asp"-->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<title>无标题文档</title>
<link href="images/skin/Css_1/1.css" rel="stylesheet" type="text/css">
</head>
<body>
<form name="form1" method="post" action="upfile.asp" enctype="multipart/form-data" >
<input type="hidden" name="act" value="upload">
<input type="hidden" name="filepath" value="../images">
<table width="100%"  border="0" align="center" cellpadding="0" cellspacing="0" >
<tr class="hback">
<td>
<input type="file" name="file1" width=200  value="" style="font-family: 宋体; font-size: 9pt">
<input type="submit" name="Submit" value="提交/Submit" >
</td>
</tr>
</table>
</form>
</body>
</html>
