<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<title>网站内容管理系统--管理后台</title>
<link href="images/skin/Css_1/1.css" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
-->
</style>
</head>
<body scroll="no">
<table width="100%" height="51" border="0" cellpadding="0" cellspacing="0" background="images/skin/Css_1/1_bg_01.gif">
	<tr>
		<td valign="top">
			<table width="100%" height="39" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="167" valign="top"><img src="images/skin/Css_1/1_logo.gif" width="167" height="39"></td>
					<td valign="bottom">
						<table width="100%" height="25" border="0" cellpadding="2" cellspacing="2">
							<tr>
								<td width="87" align="right" valign="middle">
									<div align="left"><img src="Images/changeskin.gif" width="86" height="12" border="0" usemap="#Map"></div>
								</td>
								<td align="right" valign="middle">
									<div align="center"></div>
								</td>
							  <td align="right" valign="middle">〖<a href="../" target="_blank" class="ischeck">网站首页</a>〗&nbsp;|&nbsp;〖<a href="Admin.asp" target="ContentFrame" class="ischeck">管理员</a>〗&nbsp;|&nbsp;〖<a href="../Site-space.Asp" target="ContentFrame" class="ischeck">空间使用情况</a>〗&nbsp;|&nbsp;〖<a href="Loginout.asp" target="_top" class="ischeck">退出系统</a>〗&nbsp;&nbsp;</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>